Set CONDA_FORCE_32BIT *after* updating conda!
Setting this flag during the update causes an error on miniconda36:

   CondaValueError: cannot use CONDA_FORCE_32BIT=1 in base env