Update to MAD-X 5.02.11
Also upgrade Travis build environment to Trusty Tahr because of build problems
with gfortran 4.6 on Precise:

    [ 24%] Building Fortran object libs/ptc/src/CMakeFiles/ptc.dir/Sn_mad_like.f90.o
    cd /«PKGBUILDDIR»/obj-x86_64-linux-gnu/libs/ptc/src && /usr/bin/gfortran  -Dptc_EXPORTS -D_NTPSA -D_GFORTRAN -D_FULL -D_VERSION=5.02.11 -D_VERSION_NUM=50211 -D_VERSION_DATE=2016.10.11 -D_VERSION_OSTYPE=Linux -D_LINUX -fno-range-check -fno-f2c -cpp  -g -funroll-loops -O4 -J../../../include/fortran/madX -fPIC   -c /«PKGBUILDDIR»/libs/ptc/src/Sn_mad_like.f90 -o CMakeFiles/ptc.dir/Sn_mad_like.f90.o
    /«PKGBUILDDIR»/libs/ptc/src/Sn_mad_like.f90:341.19:

      INTERFACE pancake
                       1
    Error: DERIVED attribute of 'pancake' conflicts with PROCEDURE attribute at (1)
    /«PKGBUILDDIR»/libs/ptc/src/Sn_mad_like.f90:342.21:

         MODULE PROCEDURE pancake_tilt
                         1
    Error: MODULE PROCEDURE at (1) must be in a generic module interface
    /«PKGBUILDDIR»/libs/ptc/src/Sn_mad_like.f90:343.5:

      end  INTERFACE
         1
    Error: Expecting END MODULE statement at (1)