Fix install error
Again there is a confusing error under the following conditions:

- python2
- having installed via `python setup.py install`
- only when reinstalling using the same command

Apparently, it seems to be caused by having a separate top level python
module. So, I'll just move the 'rpyc_classic_stdio.py' into the cpymad
package for now.

Not sure, what the reason for this is. Seems to me like yet another bug
in setuptools. It is possible that the installation succeeds anyway
since this occurs at the very and of the setup process.

The complete traceback is:

    Installed <site-packages>/cern_pymad-0.5-py2.7-linux-x86_64.egg
    Processing dependencies for cern-pymad==0.5
    Traceback (most recent call last):
      File "setup.py", line 159, in <module>
        'rpyc>=3.2'
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<site-packages>/setuptools/command/install.py", line 73, in run
        self.do_egg_install()
      File "<site-packages>/setuptools/command/install.py", line 101, in do_egg_install
        cmd.run()
      File "<site-packages>/setuptools/command/easy_install.py", line 380, in run
        self.easy_install(spec, not self.no_deps)
      File "<site-packages>/setuptools/command/easy_install.py", line 604, in easy_install
        return self.install_item(None, spec, tmpdir, deps, True)
      File "<site-packages>/setuptools/command/easy_install.py", line 655, in install_item
        self.process_distribution(spec, dist, deps)
      File "<site-packages>/setuptools/command/easy_install.py", line 706, in process_distribution
        [requirement], self.local_index, self.easy_install
      File "<site-packages>/pkg_resources.py", line 631, in resolve
        requirements.extend(dist.requires(req.extras)[::-1])
      File "<site-packages>/pkg_resources.py", line 2489, in requires
        dm = self._dep_map
      File "<site-packages>/pkg_resources.py", line 2474, in _dep_map
        for extra,reqs in split_sections(self._get_metadata(name)):
      File "<site-packages>/pkg_resources.py", line 2964, in split_sections
        for line in yield_lines(s):
      File "<site-packages>/pkg_resources.py", line 2161, in yield_lines
        for ss in strs:
      File "<site-packages>/pkg_resources.py", line 2503, in _get_metadata
        for line in self.get_metadata_lines(name):
      File "<site-packages>/pkg_resources.py", line 1429, in get_metadata_lines
        return yield_lines(self.get_metadata(name))
      File "<site-packages>/pkg_resources.py", line 1421, in get_metadata
        return self._get(self._fn(self.egg_info,name))
      File "<site-packages>/pkg_resources.py", line 1486, in _get
        return self.loader.get_data(path)
    zipimport.ZipImportError: bad local file header in <site-packages>ython2.7/site-packages/cern_pymad-0.5-py2.7-linux-x86_64.egg