Fix error due to cython knowing too much about split ;)
By defining the return type of _str() as unicode, cython gains knowledge
about the expected parameters of the unicode.split method:

        unicode.split(unicode, int)

and raises:

      File "cpymad/libmadx.pyx", line 980, in cpymad.libmadx._split_header_line
        _, key, kind, value = _str(header_line).split(None, 3)
    TypeError: coercing to Unicode: need string or buffer, NoneType found

which is wrong, since clearly, split does accept None usually.